// 각 슬라이드의 데이터 구조를 위한 타입 정의
export interface SlideData {
  id: number;
  title: string;
  description: string;
  imageUrl: string;
  winRate: string;     // 승률
  pickRate: string;    // 픽률
  banRate: string;     // 밴률
  points: string;      // 주요 변경 사항 또는 주목해야 할 포인트
}

// 슬라이드 데이터 배열
const slidesData: SlideData[] = [
  // 탑 라인
  {
    id: 1,
    title: '가렌 (탑)',
    description: '14.17 패치 승률 50.2%, 픽률 7.8%, 밴률 0.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg',
    winRate: '50.2%',
    pickRate: '7.8%',
    banRate: '0.5%',
    points: 'Q - 결정타: 추가 피해량 10% 증가, E - 심판: 방어력 30% 증가',
  },
  {
    id: 2,
    title: '다리우스 (탑)',
    description: '14.17 패치 승률 51.0%, 픽률 9.3%, 밴률 10.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg',
    winRate: '51.0%',
    pickRate: '9.3%',
    banRate: '10.5%',
    points: 'R - 녹서스의 단두대: 피해량 20% 증가',
  },
  {
    id: 3,
    title: '모데카이저 (탑)',
    description: '14.17 패치 승률 52.8%, 픽률 6.1%, 밴률 7.3%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg',
    winRate: '52.8%',
    pickRate: '6.1%',
    banRate: '7.3%',
    points: 'Q - 파멸의 손아귀: 피해량 15% 증가',
  },
  {
    id: 4,
    title: '말파이트 (탑)',
    description: '14.17 패치 승률 53.1%, 픽률 4.9%, 밴률 5.1%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg',
    winRate: '53.1%',
    pickRate: '4.9%',
    banRate: '5.1%',
    points: 'R - 멈출 수 없는 힘: 쿨다운 10초 감소',
  },
  {
    id: 5,
    title: '요릭 (탑)',
    description: '14.17 패치 승률 50.9%, 픽률 2.3%, 밴률 1.7%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_0.jpg',
    winRate: '50.9%',
    pickRate: '2.3%',
    banRate: '1.7%',
    points: 'E - 악령의 전조: 투사체 속도 증가',
  },

  // 미드 라인
  {
    id: 6,
    title: '아리 (미드)',
    description: '14.17 패치 승률 52.3%, 픽률 8.1%, 밴률 2.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg',
    winRate: '52.3%',
    pickRate: '8.1%',
    banRate: '2.2%',
    points: 'W - 여우불: 피해량 50 → 55, E - 매혹: 쿨다운 12초 → 10초',
  },
  {
    id: 7,
    title: '카타리나 (미드)',
    description: '14.17 패치 승률 48.9%, 픽률 5.5%, 밴률 6.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg',
    winRate: '48.9%',
    pickRate: '5.5%',
    banRate: '6.8%',
    points: 'R - 죽음의 연꽃: 추가 공격력 비례 피해량 증가',
  },
  {
    id: 8,
    title: '제드 (미드)',
    description: '14.17 패치 승률 47.8%, 픽률 10.3%, 밴률 35.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg',
    winRate: '47.8%',
    pickRate: '10.3%',
    banRate: '35.2%',
    points: 'Q - 죽음의 표식: 기본 피해량 10% 증가',
  },
  {
    id: 9,
    title: '탈론 (미드)',
    description: '14.17 패치 승률 49.9%, 픽률 5.1%, 밴률 6.1%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_0.jpg',
    winRate: '49.9%',
    pickRate: '5.1%',
    banRate: '6.1%',
    points: 'W - 갈퀴손: 피해량 20% 증가',
  },
  {
    id: 10,
    title: '빅토르 (미드)',
    description: '14.17 패치 승률 50.0%, 픽률 4.9%, 밴률 1.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg',
    winRate: '50.0%',
    pickRate: '4.9%',
    banRate: '1.2%',
    points: 'Q - 힘의 흡수: 보호막 효과 10% 증가',
  },

  // 정글 라인
  {
    id: 26,
    title: '피들스틱 (정글)',
    description: '14.17 패치 승률 49.0%, 픽률 3.7%, 밴률 1.6%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg',
    winRate: '49.0%',
    pickRate: '3.7%',
    banRate: '1.6%',
    points: 'Q - 화살 세례: 공격 속도 30% 증가, E - 차오르는 공포: 피해량 10% 증가',
  },
  {
    id: 11,
    title: '킨드레드 (정글)',
    description: '14.17 패치 승률 49.0%, 픽률 3.7%, 밴률 1.6%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_0.jpg',
    winRate: '49.0%',
    pickRate: '3.7%',
    banRate: '1.6%',
    points: 'Q - 화살 세례: 공격 속도 30% 증가, E - 차오르는 공포: 피해량 10% 증가',
  },
  {
    id: 12,
    title: '리신 (정글)',
    description: '14.17 패치 승률 47.5%, 픽률 12.4%, 밴률 5.6%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_4.jpg',
    winRate: '47.5%',
    pickRate: '12.4%',
    banRate: '5.6%',
    points: 'R - 용의 분노: 쿨다운 20초 감소',
  },
  {
    id: 13,
    title: '세주아니 (정글)',
    description: '14.17 패치 승률 51.8%, 픽률 7.2%, 밴률 3.1%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg',
    winRate: '51.8%',
    pickRate: '7.2%',
    banRate: '3.1%',
    points: 'R - 극한의 추위: 기절 지속시간 증가',
  },
  {
    id: 14,
    title: '카직스 (정글)',
    description: '14.17 패치 승률 50.3%, 픽률 9.1%, 밴률 7.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_0.jpg',
    winRate: '50.3%',
    pickRate: '9.1%',
    banRate: '7.2%',
    points: 'Q - 고립된 목표: 피해량 증가',
  },
  {
    id: 15,
    title: '녹턴 (정글)',
    description: '14.17 패치 승률 51.4%, 픽률 4.3%, 밴률 2.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg',
    winRate: '51.4%',
    pickRate: '4.3%',
    banRate: '2.8%',
    points: 'R - 공포의 어둠: 쿨다운 15초 감소',
  },

  // 원딜 라인
  {
    id: 16,
    title: '애쉬 (원딜)',
    description: '14.17 패치 승률 49.7%, 픽률 12.5%, 밴률 3.1%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg',
    winRate: '49.7%',
    pickRate: '12.5%',
    banRate: '3.1%',
    points: 'R - 마법의 수정화살: 쿨다운 100초 → 80초, W - 일제 사격: 폭 20% 감소',
  },
  {
    id: 17,
    title: '징크스 (원딜)',
    description: '14.17 패치 승률 51.2%, 픽률 9.8%, 밴률 1.4%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg',
    winRate: '51.2%',
    pickRate: '9.8%',
    banRate: '1.4%',
    points: 'Q - 미니건: 공격 속도 10% 증가',
  },
  {
    id: 18,
    title: '카이사 (원딜)',
    description: '14.17 패치 승률 50.0%, 픽률 13.0%, 밴률 2.9%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg',
    winRate: '50.0%',
    pickRate: '13.0%',
    banRate: '2.9%',
    points: 'R - 사냥 본능: 사거리 50 증가',
  },
  {
    id: 19,
    title: '이즈리얼 (원딜)',
    description: '14.17 패치 승률 48.3%, 픽률 11.1%, 밴률 0.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg',
    winRate: '48.3%',
    pickRate: '11.1%',
    banRate: '0.8%',
    points: 'Q - 신비한 화살: 마나 소모량 감소',
  },
  {
    id: 20,
    title: '사미라 (원딜)',
    description: '14.17 패치 승률 50.4%, 픽률 8.9%, 밴률 6.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_0.jpg',
    winRate: '50.4%',
    pickRate: '8.9%',
    banRate: '6.5%',
    points: 'Q - 천부의 재능: 추가 피해량 증가',
  },

  // 서폿 라인
  {
    id: 21,
    title: '레오나 (서폿)',
    description: '14.17 패치 승률 50.5%, 픽률 7.4%, 밴률 2.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg',
    winRate: '50.5%',
    pickRate: '7.4%',
    banRate: '2.5%',
    points: 'R - 태양의 분노: 기절 지속시간 증가',
  },
  {
    id: 22,
    title: '쓰레쉬 (서폿)',
    description: '14.17 패치 승률 48.9%, 픽률 10.2%, 밴률 4.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg',
    winRate: '48.9%',
    pickRate: '10.2%',
    banRate: '4.2%',
    points: 'Q - 사슬 발톱: 쿨다운 5초 감소',
  },
  {
    id: 23,
    title: '유미 (서폿)',
    description: '14.17 패치 승률 47.5%, 픽률 9.4%, 밴률 11.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg',
    winRate: '47.5%',
    pickRate: '9.4%',
    banRate: '11.2%',
    points: 'R - 최후의 장: 보호막 효과 감소',
  },
  {
    id: 24,
    title: '노틸러스 (서폿)',
    description: '14.17 패치 승률 51.3%, 픽률 6.3%, 밴률 1.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_0.jpg',
    winRate: '51.3%',
    pickRate: '6.3%',
    banRate: '1.8%',
    points: 'Q - 닻줄 견인: 기절 지속시간 증가',
  },
  {
    id: 25,
    title: '룰루 (서폿)',
    description: '14.17 패치 승률 49.4%, 픽률 8.7%, 밴률 2.6%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg',
    winRate: '49.4%',
    pickRate: '8.7%',
    banRate: '2.6%',
    points: 'W - 변이: 변이 시간 증가',
  },
  {
    id: 26,
    title: '피오라 (탑)',
    description: '14.17 패치 승률 51.5%, 픽률 3.2%, 밴률 6.0%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg',
    winRate: '51.5%',
    pickRate: '3.2%',
    banRate: '6.0%',
    points: 'Q - 결투: 기본 피해량 15% 증가',
  },
  {
    id: 27,
    title: '제이스 (탑)',
    description: '14.17 패치 승률 49.8%, 픽률 5.0%, 밴률 4.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg',
    winRate: '49.8%',
    pickRate: '5.0%',
    banRate: '4.2%',
    points: 'W - 폭풍의 벽: 방어력 10% 감소',
  },

  // 미드 라인 추가
  {
    id: 28,
    title: '룰루 (미드)',
    description: '14.17 패치 승률 48.2%, 픽률 6.0%, 밴률 3.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg',
    winRate: '48.2%',
    pickRate: '6.0%',
    banRate: '3.8%',
    points: 'W - 변이: 변이 시간 증가',
  },
  {
    id: 29,
    title: '오리아나 (미드)',
    description: '14.17 패치 승률 49.6%, 픽률 7.3%, 밴률 4.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg',
    winRate: '49.6%',
    pickRate: '7.3%',
    banRate: '4.5%',
    points: 'Q - 명령: 공: 피해량 20% 증가',
  },

  // 정글 라인 추가
  {
    id: 30,
    title: '우디르 (정글)',
    description: '14.17 패치 승률 50.7%, 픽률 6.4%, 밴률 4.8%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_0.jpg',
    winRate: '50.7%',
    pickRate: '6.4%',
    banRate: '4.8%',
    points: 'Q - 용의 분노: 공격 속도 증가',
  },
  {
    id: 31,
    title: '엘리스 (정글)',
    description: '14.17 패치 승률 48.9%, 픽률 5.1%, 밴률 3.3%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg',
    winRate: '48.9%',
    pickRate: '5.1%',
    banRate: '3.3%',
    points: 'Q - 거미 송곳니: 피해량 15% 증가',
  },

  // 원딜 라인 추가
  {
    id: 32,
    title: '케이틀린 (원딜)',
    description: '14.17 패치 승률 50.6%, 픽률 11.3%, 밴률 2.4%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg',
    winRate: '50.6%',
    pickRate: '11.3%',
    banRate: '2.4%',
    points: 'Q - 헤드샷: 피해량 10% 증가',
  },
  {
    id: 33,
    title: '트리스타나 (원딜)',
    description: '14.17 패치 승률 49.9%, 픽률 9.6%, 밴률 3.2%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_0.jpg',
    winRate: '49.9%',
    pickRate: '9.6%',
    banRate: '3.2%',
    points: 'R - 폭발! : 피해량 20% 증가',
  },

  // 서폿 라인 추가
  {
    id: 34,
    title: '알리스타 (서폿)',
    description: '14.17 패치 승률 49.3%, 픽률 8.0%, 밴률 2.9%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_0.jpg',
    winRate: '49.3%',
    pickRate: '8.0%',
    banRate: '2.9%',
    points: 'Q - 강타: 피해량 15% 증가',
  },
  {
    id: 35,
    title: '소나 (서폿)',
    description: '14.17 패치 승률 50.0%, 픽률 7.2%, 밴률 3.5%',
    imageUrl: 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_0.jpg',
    winRate: '50.0%',
    pickRate: '7.2%',
    banRate: '3.5%',
    points: 'E - 노래의 율동: 보호막 효과 10% 증가',
  },
];

export default slidesData;
